name: End-to-end tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./cypress-api-automation
          build: npm run build --if-present
          start: echo "API externa, não precisa start"
          wait-on: "https://corujice-vendas-api.onrender.com"
          wait-on-timeout: 60
          spec: cypress/api/**/*.cy.js
        env:
          CYPRESS_baseUrl: https://corujice-vendas-api.onrender.com
