name: End-to-end tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./cypress-api-automation

      - name: Run Cypress tests
        run: npm run test:api
        working-directory: ./cypress-api-automation
        env:
          CYPRESS_baseUrl: https://corujice-vendas-api.onrender.com

      - name: Upload artifacts on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            cypress-api-automation/cypress/screenshots
            cypress-api-automation/cypress/videos
